export const IMAGE_LIST_REQUEST = 'IMAGE_LIST_REQUEST';
export const IMAGE_LIST_SUCCESS = 'IMAGE_LIST_SUCCESS';
export const IMAGE_LIST_FAILURE = 'IMAGE_LIST_FAILURE';

export const IMAGE_REMOVE_REQUEST = 'IMAGE_REMOVE_REQUEST';
export const IMAGE_REMOVE_SUCCESS = 'IMAGE_REMOVE_SUCCESS';
export const IMAGE_REMOVE_FAILURE = 'IMAGE_REMOVE_FAILURE';
